name: Auto-Commit CI

permissions:
  contents: write  # Права на запись в репозиторий

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'  # Явно указываем ветку

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Check for changes
        id: changes
        run: |
          git add .
          git diff-index --quiet HEAD || echo "changes=true" >> $GITHUB_OUTPUT
          
      - name: Commit and push if changes exist
        if: steps.changes.outputs.changes == 'true'
        run: |
          git commit -m "Automated updates [skip ci]"
          git push origin main
